name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'

      - name: Install
        run: |
          npm ci

      - name: Get url
        run: echo
      - name: Test
        run: |
          npm run test-ci

      - name: Build
        run: BASE_PATH=$Base_Path npm run build
        env:
          Base_Path: ${{ format('/{0}',  github.event.repository.name) }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
